### ISSUE TITLE
[PE-D][Tester F] Add command reject alphanumeric name

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F08-2/tp#267] opened 2024-11-08 18:29 UTC
![Screenshot 2024-11-08 at 4.53.43 PM.png](https://raw.githubusercontent.com/yhanyi/ped/main/files/9acc8540-e046-4dca-b45b-2e0e1ae10ecb.png)

Despite alphanumeric names being allowed, "n/John1 Doe" was rejected

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: yhanyi/ped#8

**Comment by wkxcass** [comment] 2024-11-09 03:09
Duplicate of #275

**Closed** 2024-11-09 04:54 UTC
Labels: response.DuplicateBug
